name: ilume-iltransr-convert
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8.20
  - pip=24.3.1
  - pip:
      - gluonnlp==0.10.0
      - mxnet==1.9.1
      - numpy==1.23.5
      - safetensors==0.4.5
